[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.Bluetooth-Incoming-Port

; Tambahkan ESP_SSLClient di bawah Firebase
lib_deps = 
	mobizt/Firebase ESP32 Client
	mobizt/ESP_SSLClient

; Tambahkan baris ini agar pencarian file header lebih teliti
lib_ldf_mode = deep